name: Fetch Penguin Data and Predict

on:
  schedule:
    - cron: "30 7 * * *"  # Runs daily at 7:30 AM UTC
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  fetch_predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch Data and Make Prediction
        run: python scripts/fetch_predict.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results/index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update penguin prediction"
          git push
